name: GH Test

on:
  push:
    branches: main
  workflow_dispatch:
  workflow_call:
    inputs:
      deploy-pcf:
        description: 'Determines whether we need to deploy to PCF or not. Used to skip PCF deployment for libraries'
        required: false
        type: string
        default: 'nagesh'
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
         deploy-pcf: 'nagesh'
    - name: hello Nagesh
      run: | 
           input=${{ inputs.deploy-pcf }}
           echo ${{ inputs.deploy-pcf }}
           echo 'Hello Nagesh'
      shell: bash
  byebye:
     runs-on: ubuntu-latest
     needs: [hello]
     if: | 
         always() && 
         (needs.hello.result == 'success') &&
         (inputs.deploy-pcf == 'true')
     steps:
       - name: goodbye Nagesh
         run: echo ${{ needs.hello.result }}
         shell: bash
      
    
