name: GH Test

on:
  push:
    branches: main
  workflow_dispatch:

env: 
  DAY_OF_WEEK: Monday
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - run: | 
           echo $DAY_OF_WEEK
           echo 'Hello Nagesh'
         shell: bash
  byebye:
     runs-on: ubuntu-latest
     needs: [hello]
     if: | 
         always() && 
         (needs.hello.result == 'success') &&
         (inputs.deploy-pcf == 'nagesh')
     steps:
       - name: goodbye Nagesh
         run: echo ${{ needs.hello.result }}
         shell: bash
      
    
