name: GH Test

on:
  push:
    branches: main
  workflow_dispatch:
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: hello Nagesh
      run: echo "Hello Nagesh 2"
      shell: bash
  byebye:
     runs-on: ubuntu-latest
     steps:
       - name: goodbye Nagesh
         run: echo ${{ needs.hello }}
         shell: bash
      
    
