name: GH Test

on:
  push:
    branches: main
  workflow_dispatch:

env: 
  DAY_OF_WEEK: Monday
  TAG_EVENT: ${{ true }}
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - run: | 
           echo $TAG_EVENT
           echo 'Hello Nagesh'
         shell: bash
  byebye:
     runs-on: ubuntu-latest
     needs: [hello]
     if: ${{ TAG_EVENT == 'true' }}
     steps:
       - name: goodbye Nagesh
         run: echo ${{ needs.hello.result }}
         shell: bash
      
    
