name: GH Test

on:
  push:
    branches: main
  workflow_dispatch:

env: 
  DAY_OF_WEEK: Monday
  TAG_EVENT: ${{ true }}
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - run: | 
           echo $DAY_OF_WEEK
           echo 'Hello Nagesh'
         shell: bash
  byebye:
     name: call-myflow
     uses: https://github.com/maganti99/JavaExampe1/blob/main/.github/workflows/myflow.yaml@main
    
      
    
