name: CF Deploy to DEV

on:
  workflow_call:
    inputs:
      app-name:
        description: 'Application Name'
        required: true
        type: string
      skip-tests:
        description: 'Whether to exclude unit tests from the build'
        required: false
        type: boolean
        default: false

jobs:
  byebye:
     runs-on: ubuntu-latest
     if: ${{ (!inputs.skip-tests)  && (2 == 2)  }}
     steps:
       - name: goodbye Nagesh
         run: echo ${{ inputs.app-name }}
         shell: bash
