name: CF Deploy to DEV

on:
  workflow_call:
    inputs:
      app-name:
        description: 'Application Name'
        required: true
        type: string

jobs:
  byebye:
     runs-on: ubuntu-latest
     if: ${{ (1 == 1)  && (2 == 2)  }}
     steps:
       - name: goodbye Nagesh
         run: echo ${{ inputs.app-name }}
         shell: bash
